#
# Module manifest for module 'Omnicit.PIM'
#
# Generated by: Omnicit
#
# Generated on: 2026-03-25
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Omnicit.PIM.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = 'ed16ca8d-c9c0-4987-90b9-749edc96ebb8'

# Author of this module
    Author = 'Omnicit (originally by Justin Grote @justinwgrote)'

# Company or vendor of this module
CompanyName = 'Omnicit'

# Copyright statement for this module
Copyright = '(c) Omnicit. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Entra ID Privileged Identity Management (PIM) Self Activation Commands for Directory Roles, Azure Resources, and Entra ID Groups'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
    RequiredModules  = @(
        @{ ModuleName = 'Az.Resources'; ModuleVersion = '9.0.3' }
        @{ ModuleName = 'Microsoft.Graph.Authentication'; ModuleVersion = '2.36.0' }
    )

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
    # Disabled: TypesToProcess re-registers type members on every Import-Module -Force but Remove-Module does NOT
    # clean type data, so the second test file import fails with "member is already present" errors,
    # preventing all public functions from loading. Types are loaded via Update-TypeData -AppendPath in the psm1 instead.
    TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
    # Disabled: FormatsToProcess uses AppendPath internally, so Az.Resources formats (loaded via RequiredModules)
    # take precedence over ours for Az-native types. Formats are loaded via Update-FormatData -PrependPath in the psm1 instead.
    # Ref: https://github.com/PowerShell/PowerShell/issues/17345 (closed for inactivity, not fixed — confirmed still an issue Feb 2025)
    # FormatsToProcess = @(...)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('PIM', 'Azure', 'EntraID', 'ActiveDirectory', 'Identity', 'Privileged')

        # A URL to the license for this module.
            LicenseUri = 'https://github.com/Omnicit/Omnicit.PIM/LICENSE'

        # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Omnicit/Omnicit.PIM'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = ''

        # Prerelease string of this module
        Prerelease =  ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}












